build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=cover.clover'
                coverage:
                    file: 'cover.clover'
                    format: 'clover'
checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
tools:
  php_code_coverage: true
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ['src']
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_cpd:
    enabled: true
