language: php

php:
  - 7.1

sudo: false

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - composer test-with-coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
