<?php

namespace Phrest\API;

class ErrorCodes
{
    public function getErrorCodes()
    {
        $reflectionClass = new \ReflectionClass($this);
        $errorCodes = $reflectionClass->getConstants();
        unset($errorCodes['LAST_PHREST_ERROR_CODE']);
        asort($errorCodes);
        return $errorCodes;
    }

    const UNKNOWN = 0;

    const INTERNAL_SERVER_ERROR = 1;

    const JSON_DECODE_ERROR = 2;
    const JSON_DECODE_ERROR_DEPTH = 3;
    const JSON_DECODE_ERROR_STATE_MISMATCH = 4;
    const JSON_DECODE_ERROR_CTRL_CHAR = 5;
    const JSON_DECODE_ERROR_SYNTAX = 6;
    const JSON_DECODE_ERROR_UTF8 = 7;
    const JSON_DECODE_ERROR_RECURSION = 8;
    const JSON_DECODE_ERROR_INF_OR_NAN = 9;
    const JSON_DECODE_ERROR_UNSUPPORTED_TYPE = 10;

    const REQUEST_VALIDATION_ADDITIONAL_ITEMS = 11;
    const REQUEST_VALIDATION_ADDITIONAL_PROP = 12;
    const REQUEST_VALIDATION_ALL_OF = 13;
    const REQUEST_VALIDATION_ANY_OF = 14;
    const REQUEST_VALIDATION_DEPENDENCIES = 15;
    const REQUEST_VALIDATION_DISALLOW = 16;
    const REQUEST_VALIDATION_DIVISIBLE_BY = 17;
    const REQUEST_VALIDATION_ENUM = 18;
    const REQUEST_VALIDATION_EXCLUSIVE_MAXIMUM = 19;
    const REQUEST_VALIDATION_EXCLUSIVE_MINIMUM = 20;
    const REQUEST_VALIDATION_FORMAT = 21;
    const REQUEST_VALIDATION_MAXIMUM = 22;
    const REQUEST_VALIDATION_MAX_ITEMS = 23;
    const REQUEST_VALIDATION_MAX_LENGTH = 24;
    const REQUEST_VALIDATION_MAX_PROPERTIES = 25;
    const REQUEST_VALIDATION_MINIMUM = 26;
    const REQUEST_VALIDATION_MIN_ITEMS = 27;
    const REQUEST_VALIDATION_MIN_LENGTH = 28;
    const REQUEST_VALIDATION_MIN_PROPERTIES = 29;
    const REQUEST_VALIDATION_MISSING_MAXIMUM = 30;
    const REQUEST_VALIDATION_MISSING_MINIMUM = 31;
    const REQUEST_VALIDATION_MULTIPLE_OF = 32;
    const REQUEST_VALIDATION_NOT = 33;
    const REQUEST_VALIDATION_ONE_OF = 34;
    const REQUEST_VALIDATION_PATTERN = 35;
    const REQUEST_VALIDATION_PREGEX = 36;
    const REQUEST_VALIDATION_REQUIRED = 37;
    const REQUEST_VALIDATION_REQUIRES = 38;
    const REQUEST_VALIDATION_SCHEMA = 39;
    const REQUEST_VALIDATION_TYPE = 40;
    const REQUEST_VALIDATION_UNIQUE_ITEMS = 41;

    const REQUEST_PARAMETER_VALIDATION = 42;
    const PATH_NOT_FOUND = 43;

    const LAST_PHREST_ERROR_CODE = 43;
}